generatorName: dart-dio
outputDir: ./lib/generated/api
additionalProperties:
  pubName: e_shop_api
  pubVersion: 1.0.0
  pubSdkConstraint: '>=3.10.8 <4.0.0'
  nullSafe: true
  serializationLibrary: built_value
  useEnumExtension: true
  nullableFields: true
  legacyDiscriminatorBehavior: false
  enumUnknownDefaultCase: true
  dateLibrary: core

